// @generated by protoc-gen-es v2.15.0 with parameter "target=ts,import_extension=js"
// @generated from file reactor_wire/v1/common.proto (package reactor_wire.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file reactor_wire/v1/common.proto.
 */
export const file_reactor_wire_v1_common: GenFile = /*@__PURE__*/
  fileDesc("ChxyZWFjdG9yX3dpcmUvdjEvY29tbW9uLnByb3RvEg9yZWFjdG9yX3dpcmUudjEiJgoFRXJyb3ISDAoEY29kZRgBIAEoCRIPCgdtZXNzYWdlGAIgASgJKn8KC01lc3NhZ2VLaW5kEhwKGE1FU1NBR0VfS0lORF9VTlNQRUNJRklFRBAAEhgKFE1FU1NBR0VfS0lORF9SRVFVRVNUEAESGQoVTUVTU0FHRV9LSU5EX1JFU1BPTlNFEAISHQoZTUVTU0FHRV9LSU5EX05PVElGSUNBVElPThADYgZwcm90bzM");

/**
 * Payload of a failed response, correlated to its request by request_id.
 *
 * @generated from message reactor_wire.v1.Error
 */
export type Error = Message<"reactor_wire.v1.Error"> & {
  /**
   * @generated from field: string code = 1;
   */
  code: string;

  /**
   * @generated from field: string message = 2;
   */
  message: string;
};

/**
 * Describes the message reactor_wire.v1.Error.
 * Use `create(ErrorSchema)` to create a new message.
 */
export const ErrorSchema: GenMessage<Error> = /*@__PURE__*/
  messageDesc(file_reactor_wire_v1_common, 0);

/**
 * Framing shared by every channel message. A request expects a correlated
 * response (matched by request_id); a notification is fire-and-forget.
 *
 * @generated from enum reactor_wire.v1.MessageKind
 */
export enum MessageKind {
  /**
   * @generated from enum value: MESSAGE_KIND_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: MESSAGE_KIND_REQUEST = 1;
   */
  REQUEST = 1,

  /**
   * @generated from enum value: MESSAGE_KIND_RESPONSE = 2;
   */
  RESPONSE = 2,

  /**
   * @generated from enum value: MESSAGE_KIND_NOTIFICATION = 3;
   */
  NOTIFICATION = 3,
}

/**
 * Describes the enum reactor_wire.v1.MessageKind.
 */
export const MessageKindSchema: GenEnum<MessageKind> = /*@__PURE__*/
  enumDesc(file_reactor_wire_v1_common, 0);

