// @generated by protoc-gen-es v2.15.0 with parameter "target=ts,import_extension=js"
// @generated from file reactor_wire/v1/control.proto (package reactor_wire.v1, syntax proto3)

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Error, MessageKind } from "./common_pb.js";
import { file_reactor_wire_v1_common } from "./common_pb.js";
import type { ClipFailed, ClipReady, FileUploaded, ModelSchema, Moderation, Ping, RequestClip, RequestRecording, RequestSchema } from "./platform_pb.js";
import { file_reactor_wire_v1_platform } from "./platform_pb.js";
import type { PauseTrack, PublishTrack, PublishTrackResponse, ResumeTrack, UnpublishTrack } from "./track_pb.js";
import { file_reactor_wire_v1_track } from "./track_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file reactor_wire/v1/control.proto.
 */
export const file_reactor_wire_v1_control: GenFile = /*@__PURE__*/
  fileDesc("Ch1yZWFjdG9yX3dpcmUvdjEvY29udHJvbC5wcm90bxIPcmVhY3Rvcl93aXJlLnYxIvcEChRDb250cm9sQ2xpZW50TWVzc2FnZRISCgpyZXF1ZXN0X2lkGAEgASgJEioKBGtpbmQYAiABKA4yHC5yZWFjdG9yX3dpcmUudjEuTWVzc2FnZUtpbmQSJQoEcGluZxgKIAEoCzIVLnJlYWN0b3Jfd2lyZS52MS5QaW5nSAASOAoOcmVxdWVzdF9zY2hlbWEYCyABKAsyHi5yZWFjdG9yX3dpcmUudjEuUmVxdWVzdFNjaGVtYUgAEjYKDWZpbGVfdXBsb2FkZWQYDCABKAsyHS5yZWFjdG9yX3dpcmUudjEuRmlsZVVwbG9hZGVkSAASNAoMcmVxdWVzdF9jbGlwGA0gASgLMhwucmVhY3Rvcl93aXJlLnYxLlJlcXVlc3RDbGlwSAASPgoRcmVxdWVzdF9yZWNvcmRpbmcYDiABKAsyIS5yZWFjdG9yX3dpcmUudjEuUmVxdWVzdFJlY29yZGluZ0gAEjYKDXB1Ymxpc2hfdHJhY2sYDyABKAsyHS5yZWFjdG9yX3dpcmUudjEuUHVibGlzaFRyYWNrSAASMgoLcGF1c2VfdHJhY2sYECABKAsyGy5yZWFjdG9yX3dpcmUudjEuUGF1c2VUcmFja0gAEjQKDHJlc3VtZV90cmFjaxgRIAEoCzIcLnJlYWN0b3Jfd2lyZS52MS5SZXN1bWVUcmFja0gAEjoKD3VucHVibGlzaF90cmFjaxgSIAEoCzIfLnJlYWN0b3Jfd2lyZS52MS5VbnB1Ymxpc2hUcmFja0gAEicKBWVycm9yGCggASgLMhYucmVhY3Rvcl93aXJlLnYxLkVycm9ySABCCQoHcGF5bG9hZCKZAwoUQ29udHJvbFNlcnZlck1lc3NhZ2USEgoKcmVxdWVzdF9pZBgBIAEoCRIqCgRraW5kGAIgASgOMhwucmVhY3Rvcl93aXJlLnYxLk1lc3NhZ2VLaW5kEjQKDG1vZGVsX3NjaGVtYRgKIAEoCzIcLnJlYWN0b3Jfd2lyZS52MS5Nb2RlbFNjaGVtYUgAEjAKCmNsaXBfcmVhZHkYCyABKAsyGi5yZWFjdG9yX3dpcmUudjEuQ2xpcFJlYWR5SAASMgoLY2xpcF9mYWlsZWQYDCABKAsyGy5yZWFjdG9yX3dpcmUudjEuQ2xpcEZhaWxlZEgAEjEKCm1vZGVyYXRpb24YDSABKAsyGy5yZWFjdG9yX3dpcmUudjEuTW9kZXJhdGlvbkgAEj4KDXB1Ymxpc2hfdHJhY2sYDiABKAsyJS5yZWFjdG9yX3dpcmUudjEuUHVibGlzaFRyYWNrUmVzcG9uc2VIABInCgVlcnJvchgoIAEoCzIWLnJlYWN0b3Jfd2lyZS52MS5FcnJvckgAQgkKB3BheWxvYWRiBnByb3RvMw", [file_reactor_wire_v1_common, file_reactor_wire_v1_platform, file_reactor_wire_v1_track]);

/**
 * Control channel, client to runtime. Carries all platform and track traffic.
 *
 * @generated from message reactor_wire.v1.ControlClientMessage
 */
export type ControlClientMessage = Message<"reactor_wire.v1.ControlClientMessage"> & {
  /**
   * @generated from field: string request_id = 1;
   */
  requestId: string;

  /**
   * @generated from field: reactor_wire.v1.MessageKind kind = 2;
   */
  kind: MessageKind;

  /**
   * @generated from oneof reactor_wire.v1.ControlClientMessage.payload
   */
  payload: {
    /**
     * @generated from field: reactor_wire.v1.Ping ping = 10;
     */
    value: Ping;
    case: "ping";
  } | {
    /**
     * @generated from field: reactor_wire.v1.RequestSchema request_schema = 11;
     */
    value: RequestSchema;
    case: "requestSchema";
  } | {
    /**
     * @generated from field: reactor_wire.v1.FileUploaded file_uploaded = 12;
     */
    value: FileUploaded;
    case: "fileUploaded";
  } | {
    /**
     * @generated from field: reactor_wire.v1.RequestClip request_clip = 13;
     */
    value: RequestClip;
    case: "requestClip";
  } | {
    /**
     * @generated from field: reactor_wire.v1.RequestRecording request_recording = 14;
     */
    value: RequestRecording;
    case: "requestRecording";
  } | {
    /**
     * @generated from field: reactor_wire.v1.PublishTrack publish_track = 15;
     */
    value: PublishTrack;
    case: "publishTrack";
  } | {
    /**
     * @generated from field: reactor_wire.v1.PauseTrack pause_track = 16;
     */
    value: PauseTrack;
    case: "pauseTrack";
  } | {
    /**
     * @generated from field: reactor_wire.v1.ResumeTrack resume_track = 17;
     */
    value: ResumeTrack;
    case: "resumeTrack";
  } | {
    /**
     * @generated from field: reactor_wire.v1.UnpublishTrack unpublish_track = 18;
     */
    value: UnpublishTrack;
    case: "unpublishTrack";
  } | {
    /**
     * @generated from field: reactor_wire.v1.Error error = 40;
     */
    value: Error;
    case: "error";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message reactor_wire.v1.ControlClientMessage.
 * Use `create(ControlClientMessageSchema)` to create a new message.
 */
export const ControlClientMessageSchema: GenMessage<ControlClientMessage> = /*@__PURE__*/
  messageDesc(file_reactor_wire_v1_control, 0);

/**
 * Control channel, runtime to client. Carries all platform and track traffic.
 *
 * @generated from message reactor_wire.v1.ControlServerMessage
 */
export type ControlServerMessage = Message<"reactor_wire.v1.ControlServerMessage"> & {
  /**
   * @generated from field: string request_id = 1;
   */
  requestId: string;

  /**
   * @generated from field: reactor_wire.v1.MessageKind kind = 2;
   */
  kind: MessageKind;

  /**
   * @generated from oneof reactor_wire.v1.ControlServerMessage.payload
   */
  payload: {
    /**
     * @generated from field: reactor_wire.v1.ModelSchema model_schema = 10;
     */
    value: ModelSchema;
    case: "modelSchema";
  } | {
    /**
     * @generated from field: reactor_wire.v1.ClipReady clip_ready = 11;
     */
    value: ClipReady;
    case: "clipReady";
  } | {
    /**
     * @generated from field: reactor_wire.v1.ClipFailed clip_failed = 12;
     */
    value: ClipFailed;
    case: "clipFailed";
  } | {
    /**
     * @generated from field: reactor_wire.v1.Moderation moderation = 13;
     */
    value: Moderation;
    case: "moderation";
  } | {
    /**
     * @generated from field: reactor_wire.v1.PublishTrackResponse publish_track = 14;
     */
    value: PublishTrackResponse;
    case: "publishTrack";
  } | {
    /**
     * @generated from field: reactor_wire.v1.Error error = 40;
     */
    value: Error;
    case: "error";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message reactor_wire.v1.ControlServerMessage.
 * Use `create(ControlServerMessageSchema)` to create a new message.
 */
export const ControlServerMessageSchema: GenMessage<ControlServerMessage> = /*@__PURE__*/
  messageDesc(file_reactor_wire_v1_control, 1);

