// @generated by protoc-gen-es v2.15.0 with parameter "target=ts,import_extension=js"
// @generated from file reactor_wire/v1/data.proto (package reactor_wire.v1, syntax proto3)

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Error, MessageKind } from "./common_pb.js";
import { file_reactor_wire_v1_common } from "./common_pb.js";
import type { Command, ModelMessage } from "./model_pb.js";
import { file_reactor_wire_v1_model } from "./model_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file reactor_wire/v1/data.proto.
 */
export const file_reactor_wire_v1_data: GenFile = /*@__PURE__*/
  fileDesc("ChpyZWFjdG9yX3dpcmUvdjEvZGF0YS5wcm90bxIPcmVhY3Rvcl93aXJlLnYxIrQBChFEYXRhQ2xpZW50TWVzc2FnZRISCgpyZXF1ZXN0X2lkGAEgASgJEioKBGtpbmQYAiABKA4yHC5yZWFjdG9yX3dpcmUudjEuTWVzc2FnZUtpbmQSKwoHY29tbWFuZBgKIAEoCzIYLnJlYWN0b3Jfd2lyZS52MS5Db21tYW5kSAASJwoFZXJyb3IYKCABKAsyFi5yZWFjdG9yX3dpcmUudjEuRXJyb3JIAEIJCgdwYXlsb2FkIrkBChFEYXRhU2VydmVyTWVzc2FnZRISCgpyZXF1ZXN0X2lkGAEgASgJEioKBGtpbmQYAiABKA4yHC5yZWFjdG9yX3dpcmUudjEuTWVzc2FnZUtpbmQSMAoHbWVzc2FnZRgKIAEoCzIdLnJlYWN0b3Jfd2lyZS52MS5Nb2RlbE1lc3NhZ2VIABInCgVlcnJvchgoIAEoCzIWLnJlYWN0b3Jfd2lyZS52MS5FcnJvckgAQgkKB3BheWxvYWRiBnByb3RvMw", [file_reactor_wire_v1_common, file_reactor_wire_v1_model]);

/**
 * Data channel, client to runtime. Carries only the model's own command
 * traffic; all platform and track messages travel on the control channel.
 *
 * @generated from message reactor_wire.v1.DataClientMessage
 */
export type DataClientMessage = Message<"reactor_wire.v1.DataClientMessage"> & {
  /**
   * @generated from field: string request_id = 1;
   */
  requestId: string;

  /**
   * @generated from field: reactor_wire.v1.MessageKind kind = 2;
   */
  kind: MessageKind;

  /**
   * @generated from oneof reactor_wire.v1.DataClientMessage.payload
   */
  payload: {
    /**
     * @generated from field: reactor_wire.v1.Command command = 10;
     */
    value: Command;
    case: "command";
  } | {
    /**
     * @generated from field: reactor_wire.v1.Error error = 40;
     */
    value: Error;
    case: "error";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message reactor_wire.v1.DataClientMessage.
 * Use `create(DataClientMessageSchema)` to create a new message.
 */
export const DataClientMessageSchema: GenMessage<DataClientMessage> = /*@__PURE__*/
  messageDesc(file_reactor_wire_v1_data, 0);

/**
 * Data channel, runtime to client. Carries only the model's own emitted
 * messages.
 *
 * @generated from message reactor_wire.v1.DataServerMessage
 */
export type DataServerMessage = Message<"reactor_wire.v1.DataServerMessage"> & {
  /**
   * @generated from field: string request_id = 1;
   */
  requestId: string;

  /**
   * @generated from field: reactor_wire.v1.MessageKind kind = 2;
   */
  kind: MessageKind;

  /**
   * @generated from oneof reactor_wire.v1.DataServerMessage.payload
   */
  payload: {
    /**
     * @generated from field: reactor_wire.v1.ModelMessage message = 10;
     */
    value: ModelMessage;
    case: "message";
  } | {
    /**
     * @generated from field: reactor_wire.v1.Error error = 40;
     */
    value: Error;
    case: "error";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message reactor_wire.v1.DataServerMessage.
 * Use `create(DataServerMessageSchema)` to create a new message.
 */
export const DataServerMessageSchema: GenMessage<DataServerMessage> = /*@__PURE__*/
  messageDesc(file_reactor_wire_v1_data, 1);

