// @generated by protoc-gen-es v2.15.0 with parameter "target=ts,import_extension=js"
// @generated from file reactor_wire/v1/platform.proto (package reactor_wire.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_struct } from "@bufbuild/protobuf/wkt";
import type { JsonObject, Message } from "@bufbuild/protobuf";

/**
 * Describes the file reactor_wire/v1/platform.proto.
 */
export const file_reactor_wire_v1_platform: GenFile = /*@__PURE__*/
  fileDesc("Ch5yZWFjdG9yX3dpcmUvdjEvcGxhdGZvcm0ucHJvdG8SD3JlYWN0b3Jfd2lyZS52MSIGCgRQaW5nIg8KDVJlcXVlc3RTY2hlbWEiNwoLTW9kZWxTY2hlbWESKAoHb3BlbmFwaRgBIAEoCzIXLmdvb2dsZS5wcm90b2J1Zi5TdHJ1Y3QiUAoMRmlsZVVwbG9hZGVkEhEKCXVwbG9hZF9pZBgBIAEoCRIMCgRuYW1lGAIgASgJEhEKCW1pbWVfdHlwZRgDIAEoCRIMCgRzaXplGAQgASgDIicKC1JlcXVlc3RDbGlwEhgKEGR1cmF0aW9uX3NlY29uZHMYASABKAEiEgoQUmVxdWVzdFJlY29yZGluZyKgAQoJQ2xpcFJlYWR5EhIKCnNlc3Npb25faWQYASABKAkSDAoEa2luZBgCIAEoCRIUCgxzdGFydF9tYXJrZXIYAyABKAESEgoKZW5kX21hcmtlchgEIAEoARISCgpub3dfbWFya2VyGAUgASgBEh0KFXByZWRpY3RlZF9yZWFkeV9hdF9tcxgGIAEoAxIUCgxwbGF5bGlzdF91cmwYByABKAkiHAoKQ2xpcEZhaWxlZBIOCgZyZWFzb24YASABKAkiZgoKTW9kZXJhdGlvbhIOCgZhY3Rpb24YASABKAkSEgoKaW5wdXRfa2luZBgCIAEoCRIPCgdjb21tYW5kGAMgASgJEhIKCmNhdGVnb3JpZXMYBCADKAkSDwoHbWVzc2FnZRgFIAEoCWIGcHJvdG8z", [file_google_protobuf_struct]);

/**
 * Liveness heartbeat from the client.
 *
 * @generated from message reactor_wire.v1.Ping
 */
export type Ping = Message<"reactor_wire.v1.Ping"> & {
};

/**
 * Describes the message reactor_wire.v1.Ping.
 * Use `create(PingSchema)` to create a new message.
 */
export const PingSchema: GenMessage<Ping> = /*@__PURE__*/
  messageDesc(file_reactor_wire_v1_platform, 0);

/**
 * Request for the model's schema.
 *
 * @generated from message reactor_wire.v1.RequestSchema
 */
export type RequestSchema = Message<"reactor_wire.v1.RequestSchema"> & {
};

/**
 * Describes the message reactor_wire.v1.RequestSchema.
 * Use `create(RequestSchemaSchema)` to create a new message.
 */
export const RequestSchemaSchema: GenMessage<RequestSchema> = /*@__PURE__*/
  messageDesc(file_reactor_wire_v1_platform, 1);

/**
 * The model's schema, carried as an OpenAPI document.
 *
 * @generated from message reactor_wire.v1.ModelSchema
 */
export type ModelSchema = Message<"reactor_wire.v1.ModelSchema"> & {
  /**
   * @generated from field: google.protobuf.Struct openapi = 1;
   */
  openapi?: JsonObject | undefined;
};

/**
 * Describes the message reactor_wire.v1.ModelSchema.
 * Use `create(ModelSchemaSchema)` to create a new message.
 */
export const ModelSchemaSchema: GenMessage<ModelSchema> = /*@__PURE__*/
  messageDesc(file_reactor_wire_v1_platform, 2);

/**
 * Notification that a client upload completed and can now be referenced.
 *
 * @generated from message reactor_wire.v1.FileUploaded
 */
export type FileUploaded = Message<"reactor_wire.v1.FileUploaded"> & {
  /**
   * @generated from field: string upload_id = 1;
   */
  uploadId: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string mime_type = 3;
   */
  mimeType: string;

  /**
   * @generated from field: int64 size = 4;
   */
  size: bigint;
};

/**
 * Describes the message reactor_wire.v1.FileUploaded.
 * Use `create(FileUploadedSchema)` to create a new message.
 */
export const FileUploadedSchema: GenMessage<FileUploaded> = /*@__PURE__*/
  messageDesc(file_reactor_wire_v1_platform, 3);

/**
 * Request a clip of the last duration_seconds of output.
 *
 * @generated from message reactor_wire.v1.RequestClip
 */
export type RequestClip = Message<"reactor_wire.v1.RequestClip"> & {
  /**
   * @generated from field: double duration_seconds = 1;
   */
  durationSeconds: number;
};

/**
 * Describes the message reactor_wire.v1.RequestClip.
 * Use `create(RequestClipSchema)` to create a new message.
 */
export const RequestClipSchema: GenMessage<RequestClip> = /*@__PURE__*/
  messageDesc(file_reactor_wire_v1_platform, 4);

/**
 * Request a recording of the session so far.
 *
 * @generated from message reactor_wire.v1.RequestRecording
 */
export type RequestRecording = Message<"reactor_wire.v1.RequestRecording"> & {
};

/**
 * Describes the message reactor_wire.v1.RequestRecording.
 * Use `create(RequestRecordingSchema)` to create a new message.
 */
export const RequestRecordingSchema: GenMessage<RequestRecording> = /*@__PURE__*/
  messageDesc(file_reactor_wire_v1_platform, 5);

/**
 * A clip or recording is being prepared.
 *
 * @generated from message reactor_wire.v1.ClipReady
 */
export type ClipReady = Message<"reactor_wire.v1.ClipReady"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  /**
   * @generated from field: string kind = 2;
   */
  kind: string;

  /**
   * @generated from field: double start_marker = 3;
   */
  startMarker: number;

  /**
   * @generated from field: double end_marker = 4;
   */
  endMarker: number;

  /**
   * @generated from field: double now_marker = 5;
   */
  nowMarker: number;

  /**
   * @generated from field: int64 predicted_ready_at_ms = 6;
   */
  predictedReadyAtMs: bigint;

  /**
   * @generated from field: string playlist_url = 7;
   */
  playlistUrl: string;
};

/**
 * Describes the message reactor_wire.v1.ClipReady.
 * Use `create(ClipReadySchema)` to create a new message.
 */
export const ClipReadySchema: GenMessage<ClipReady> = /*@__PURE__*/
  messageDesc(file_reactor_wire_v1_platform, 6);

/**
 * A clip or recording request failed.
 *
 * @generated from message reactor_wire.v1.ClipFailed
 */
export type ClipFailed = Message<"reactor_wire.v1.ClipFailed"> & {
  /**
   * @generated from field: string reason = 1;
   */
  reason: string;
};

/**
 * Describes the message reactor_wire.v1.ClipFailed.
 * Use `create(ClipFailedSchema)` to create a new message.
 */
export const ClipFailedSchema: GenMessage<ClipFailed> = /*@__PURE__*/
  messageDesc(file_reactor_wire_v1_platform, 7);

/**
 * A content-moderation verdict delivered to the client. A "terminate" action
 * means the session is about to end; "warn" is informational and the session
 * continues. Fields the sender cannot attribute are left empty.
 *
 * @generated from message reactor_wire.v1.Moderation
 */
export type Moderation = Message<"reactor_wire.v1.Moderation"> & {
  /**
   * @generated from field: string action = 1;
   */
  action: string;

  /**
   * @generated from field: string input_kind = 2;
   */
  inputKind: string;

  /**
   * @generated from field: string command = 3;
   */
  command: string;

  /**
   * @generated from field: repeated string categories = 4;
   */
  categories: string[];

  /**
   * @generated from field: string message = 5;
   */
  message: string;
};

/**
 * Describes the message reactor_wire.v1.Moderation.
 * Use `create(ModerationSchema)` to create a new message.
 */
export const ModerationSchema: GenMessage<Moderation> = /*@__PURE__*/
  messageDesc(file_reactor_wire_v1_platform, 8);

