// @generated by protoc-gen-es v2.15.0 with parameter "target=ts,import_extension=js"
// @generated from file reactor_wire/v1/track.proto (package reactor_wire.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file reactor_wire/v1/track.proto.
 */
export const file_reactor_wire_v1_track: GenFile = /*@__PURE__*/
  fileDesc("ChtyZWFjdG9yX3dpcmUvdjEvdHJhY2sucHJvdG8SD3JlYWN0b3Jfd2lyZS52MSIcCgxQdWJsaXNoVHJhY2sSDAoEbmFtZRgBIAEoCSIaCgpQYXVzZVRyYWNrEgwKBG5hbWUYASABKAkiGwoLUmVzdW1lVHJhY2sSDAoEbmFtZRgBIAEoCSIeCg5VbnB1Ymxpc2hUcmFjaxIMCgRuYW1lGAEgASgJIiQKFFB1Ymxpc2hUcmFja1Jlc3BvbnNlEgwKBG5hbWUYASABKAliBnByb3RvMw");

/**
 * Request to claim the single publisher slot for an input track.
 *
 * @generated from message reactor_wire.v1.PublishTrack
 */
export type PublishTrack = Message<"reactor_wire.v1.PublishTrack"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message reactor_wire.v1.PublishTrack.
 * Use `create(PublishTrackSchema)` to create a new message.
 */
export const PublishTrackSchema: GenMessage<PublishTrack> = /*@__PURE__*/
  messageDesc(file_reactor_wire_v1_track, 0);

/**
 * Stop sending an input track without releasing the publisher slot.
 *
 * @generated from message reactor_wire.v1.PauseTrack
 */
export type PauseTrack = Message<"reactor_wire.v1.PauseTrack"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message reactor_wire.v1.PauseTrack.
 * Use `create(PauseTrackSchema)` to create a new message.
 */
export const PauseTrackSchema: GenMessage<PauseTrack> = /*@__PURE__*/
  messageDesc(file_reactor_wire_v1_track, 1);

/**
 * Resume a paused input track.
 *
 * @generated from message reactor_wire.v1.ResumeTrack
 */
export type ResumeTrack = Message<"reactor_wire.v1.ResumeTrack"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message reactor_wire.v1.ResumeTrack.
 * Use `create(ResumeTrackSchema)` to create a new message.
 */
export const ResumeTrackSchema: GenMessage<ResumeTrack> = /*@__PURE__*/
  messageDesc(file_reactor_wire_v1_track, 2);

/**
 * Release the publisher slot for an input track.
 *
 * @generated from message reactor_wire.v1.UnpublishTrack
 */
export type UnpublishTrack = Message<"reactor_wire.v1.UnpublishTrack"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message reactor_wire.v1.UnpublishTrack.
 * Use `create(UnpublishTrackSchema)` to create a new message.
 */
export const UnpublishTrackSchema: GenMessage<UnpublishTrack> = /*@__PURE__*/
  messageDesc(file_reactor_wire_v1_track, 3);

/**
 * Successful response to a PublishTrack request. A failure is carried as an
 * Error in the same response slot instead.
 *
 * @generated from message reactor_wire.v1.PublishTrackResponse
 */
export type PublishTrackResponse = Message<"reactor_wire.v1.PublishTrackResponse"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message reactor_wire.v1.PublishTrackResponse.
 * Use `create(PublishTrackResponseSchema)` to create a new message.
 */
export const PublishTrackResponseSchema: GenMessage<PublishTrackResponse> = /*@__PURE__*/
  messageDesc(file_reactor_wire_v1_track, 4);

