// @generated by protoc-gen-es v2.15.0 with parameter "target=ts,import_extension=js"
// @generated from file reactor_wire/v1/model.proto (package reactor_wire.v1, syntax proto3)

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_struct } from "@bufbuild/protobuf/wkt";
import type { JsonObject, Message } from "@bufbuild/protobuf";

/**
 * Describes the file reactor_wire/v1/model.proto.
 */
export const file_reactor_wire_v1_model: GenFile = /*@__PURE__*/
  fileDesc("ChtyZWFjdG9yX3dpcmUvdjEvbW9kZWwucHJvdG8SD3JlYWN0b3Jfd2lyZS52MSJTCg9VcGxvYWRSZWZlcmVuY2USEQoJdXBsb2FkX2lkGAEgASgJEgwKBG5hbWUYAiABKAkSEQoJbWltZV90eXBlGAMgASgJEgwKBHNpemUYBCABKAMiyAEKB0NvbW1hbmQSDAoEdHlwZRgBIAEoCRIlCgRkYXRhGAIgASgLMhcuZ29vZ2xlLnByb3RvYnVmLlN0cnVjdBI2Cgd1cGxvYWRzGAMgAygLMiUucmVhY3Rvcl93aXJlLnYxLkNvbW1hbmQuVXBsb2Fkc0VudHJ5GlAKDFVwbG9hZHNFbnRyeRILCgNrZXkYASABKAkSLwoFdmFsdWUYAiABKAsyIC5yZWFjdG9yX3dpcmUudjEuVXBsb2FkUmVmZXJlbmNlOgI4ASJDCgxNb2RlbE1lc3NhZ2USDAoEdHlwZRgBIAEoCRIlCgRkYXRhGAIgASgLMhcuZ29vZ2xlLnByb3RvYnVmLlN0cnVjdGIGcHJvdG8z", [file_google_protobuf_struct]);

/**
 * Reference to a file uploaded out of band via the presigned-URL protocol,
 * injected into a Command argument by parameter name.
 *
 * @generated from message reactor_wire.v1.UploadReference
 */
export type UploadReference = Message<"reactor_wire.v1.UploadReference"> & {
  /**
   * @generated from field: string upload_id = 1;
   */
  uploadId: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string mime_type = 3;
   */
  mimeType: string;

  /**
   * @generated from field: int64 size = 4;
   */
  size: bigint;
};

/**
 * Describes the message reactor_wire.v1.UploadReference.
 * Use `create(UploadReferenceSchema)` to create a new message.
 */
export const UploadReferenceSchema: GenMessage<UploadReference> = /*@__PURE__*/
  messageDesc(file_reactor_wire_v1_model, 0);

/**
 * A model-defined command from the client. type is the command name; the
 * arguments are a dynamic object so the protocol carries any model's schema
 * without knowing it.
 *
 * @generated from message reactor_wire.v1.Command
 */
export type Command = Message<"reactor_wire.v1.Command"> & {
  /**
   * @generated from field: string type = 1;
   */
  type: string;

  /**
   * @generated from field: google.protobuf.Struct data = 2;
   */
  data?: JsonObject | undefined;

  /**
   * @generated from field: map<string, reactor_wire.v1.UploadReference> uploads = 3;
   */
  uploads: { [key: string]: UploadReference };
};

/**
 * Describes the message reactor_wire.v1.Command.
 * Use `create(CommandSchema)` to create a new message.
 */
export const CommandSchema: GenMessage<Command> = /*@__PURE__*/
  messageDesc(file_reactor_wire_v1_model, 1);

/**
 * A model-emitted message to the client. type is the message name; the body is
 * a dynamic object.
 *
 * @generated from message reactor_wire.v1.ModelMessage
 */
export type ModelMessage = Message<"reactor_wire.v1.ModelMessage"> & {
  /**
   * @generated from field: string type = 1;
   */
  type: string;

  /**
   * @generated from field: google.protobuf.Struct data = 2;
   */
  data?: JsonObject | undefined;
};

/**
 * Describes the message reactor_wire.v1.ModelMessage.
 * Use `create(ModelMessageSchema)` to create a new message.
 */
export const ModelMessageSchema: GenMessage<ModelMessage> = /*@__PURE__*/
  messageDesc(file_reactor_wire_v1_model, 2);

