// GENERATED by scripts/generate-wire.py from canonical wire 1.20260722.6. DO NOT EDIT.
// Reactor proto definitions: Apache-2.0; google.protobuf definitions: BSD-3-Clause. See NOTICE.
import { Reader, Writer } from "./protobuf.js";
import type { WireLimits, UnknownFields } from "./protobuf.js";
export const MessageKind = { MESSAGE_KIND_UNSPECIFIED: 0, MESSAGE_KIND_REQUEST: 1, MESSAGE_KIND_RESPONSE: 2, MESSAGE_KIND_NOTIFICATION: 3 } as const;
export const Google_NullValue = { NULL_VALUE: 0 } as const;
export interface Error extends UnknownFields {
  code: string;
  message: string;
}
export const Error = {
  encode(value: Error, limits?: WireLimits): Uint8Array<ArrayBuffer> { const w = new Writer(limits); writeError(w, value); return w.finish(); },
  decode(bytes: Uint8Array, limits?: WireLimits): Error { return readError(new Reader(bytes, limits)); },
};
function writeError(w: Writer, value: Error): void {
  if (value.code !== "") {
    w.string(1, value.code);
  }
  if (value.message !== "") {
    w.string(2, value.message);
  }
  w.unknown(value);
}
function readError(r: Reader, base?: Error): Error {
  let code: string = base?.code ?? "";
  let message: string = base?.message ?? "";
  const _unknown: Uint8Array[] = [...(base?._unknown ?? [])];
  while (!r.done) { const f = r.field(); switch (f.number) {
    case 1: { r.expect(f, 2);
      code = r.string();
      break; }
    case 2: { r.expect(f, 2);
      message = r.string();
      break; }
    default: _unknown.push(r.unknown(f)); break;
  } }
  return { _unknown, code, message };
}

export interface Google_Struct extends UnknownFields {
  fields: Map<string, Google_Value>;
}
export const Google_Struct = {
  encode(value: Google_Struct, limits?: WireLimits): Uint8Array<ArrayBuffer> { const w = new Writer(limits); writeGoogle_Struct(w, value); return w.finish(); },
  decode(bytes: Uint8Array, limits?: WireLimits): Google_Struct { return readGoogle_Struct(new Reader(bytes, limits)); },
};
function writeGoogle_Struct(w: Writer, value: Google_Struct): void {
  for (const [key, item] of value.fields) w.message(1, (w) => writeGoogle_Struct_FieldsEntry(w, { key, value: item }));
  w.unknown(value);
}
function readGoogle_Struct(r: Reader, base?: Google_Struct): Google_Struct {
  const fields: Map<string, Google_Value> = new Map(base?.fields ?? []);
  const _unknown: Uint8Array[] = [...(base?._unknown ?? [])];
  while (!r.done) { const f = r.field(); switch (f.number) {
    case 1: { r.expect(f, 2);
      const entry = readGoogle_Struct_FieldsEntry(r.child(), undefined); fields.set(entry.key, entry.value ?? Google_Value.decode(new Uint8Array()));
      break; }
    default: _unknown.push(r.unknown(f)); break;
  } }
  return { _unknown, fields };
}

export interface Google_Struct_FieldsEntry extends UnknownFields {
  key: string;
  value?: Google_Value;
}
export const Google_Struct_FieldsEntry = {
  encode(value: Google_Struct_FieldsEntry, limits?: WireLimits): Uint8Array<ArrayBuffer> { const w = new Writer(limits); writeGoogle_Struct_FieldsEntry(w, value); return w.finish(); },
  decode(bytes: Uint8Array, limits?: WireLimits): Google_Struct_FieldsEntry { return readGoogle_Struct_FieldsEntry(new Reader(bytes, limits)); },
};
function writeGoogle_Struct_FieldsEntry(w: Writer, value: Google_Struct_FieldsEntry): void {
  if (value.key !== "") {
    w.string(1, value.key);
  }
  if (value.value !== undefined) {
    { const messageValue = value.value; w.message(2, (w) => writeGoogle_Value(w, messageValue)); }
  }
  w.unknown(value);
}
function readGoogle_Struct_FieldsEntry(r: Reader, base?: Google_Struct_FieldsEntry): Google_Struct_FieldsEntry {
  let key: string = base?.key ?? "";
  let value: Google_Value | undefined = base?.value;
  const _unknown: Uint8Array[] = [...(base?._unknown ?? [])];
  while (!r.done) { const f = r.field(); switch (f.number) {
    case 1: { r.expect(f, 2);
      key = r.string();
      break; }
    case 2: { r.expect(f, 2);
      value = readGoogle_Value(r.child(), value);
      break; }
    default: _unknown.push(r.unknown(f)); break;
  } }
  return { _unknown, key, ...(value === undefined ? {} : { value }) };
}

export interface Google_Value extends UnknownFields {
  kind?: { case: "null_value"; value: number } | { case: "number_value"; value: number } | { case: "string_value"; value: string } | { case: "bool_value"; value: boolean } | { case: "struct_value"; value: Google_Struct } | { case: "list_value"; value: Google_ListValue };
}
export const Google_Value = {
  encode(value: Google_Value, limits?: WireLimits): Uint8Array<ArrayBuffer> { const w = new Writer(limits); writeGoogle_Value(w, value); return w.finish(); },
  decode(bytes: Uint8Array, limits?: WireLimits): Google_Value { return readGoogle_Value(new Reader(bytes, limits)); },
};
function writeGoogle_Value(w: Writer, value: Google_Value): void {
  if (value.kind?.case === "null_value") {
    w.int32(1, value.kind.value);
  }
  if (value.kind?.case === "number_value") {
    w.double(2, value.kind.value);
  }
  if (value.kind?.case === "string_value") {
    w.string(3, value.kind.value);
  }
  if (value.kind?.case === "bool_value") {
    w.bool(4, value.kind.value);
  }
  if (value.kind?.case === "struct_value") {
    { const messageValue = value.kind.value; w.message(5, (w) => writeGoogle_Struct(w, messageValue)); }
  }
  if (value.kind?.case === "list_value") {
    { const messageValue = value.kind.value; w.message(6, (w) => writeGoogle_ListValue(w, messageValue)); }
  }
  w.unknown(value);
}
function readGoogle_Value(r: Reader, base?: Google_Value): Google_Value {
  let kind: Google_Value["kind"] = base?.kind;
  const _unknown: Uint8Array[] = [...(base?._unknown ?? [])];
  while (!r.done) { const f = r.field(); switch (f.number) {
    case 1: { r.expect(f, 0);
      kind = { case: "null_value", value: r.int32() };
      break; }
    case 2: { r.expect(f, 1);
      kind = { case: "number_value", value: r.double() };
      break; }
    case 3: { r.expect(f, 2);
      kind = { case: "string_value", value: r.string() };
      break; }
    case 4: { r.expect(f, 0);
      kind = { case: "bool_value", value: r.bool() };
      break; }
    case 5: { r.expect(f, 2);
      kind = { case: "struct_value", value: readGoogle_Struct(r.child(), kind?.case === "struct_value" ? kind.value : undefined) };
      break; }
    case 6: { r.expect(f, 2);
      kind = { case: "list_value", value: readGoogle_ListValue(r.child(), kind?.case === "list_value" ? kind.value : undefined) };
      break; }
    default: _unknown.push(r.unknown(f)); break;
  } }
  return { _unknown, ...(kind === undefined ? {} : { kind }) };
}

export interface Google_ListValue extends UnknownFields {
  values: Array<Google_Value>;
}
export const Google_ListValue = {
  encode(value: Google_ListValue, limits?: WireLimits): Uint8Array<ArrayBuffer> { const w = new Writer(limits); writeGoogle_ListValue(w, value); return w.finish(); },
  decode(bytes: Uint8Array, limits?: WireLimits): Google_ListValue { return readGoogle_ListValue(new Reader(bytes, limits)); },
};
function writeGoogle_ListValue(w: Writer, value: Google_ListValue): void {
  for (const item of value.values) {
    { const messageValue = item; w.message(1, (w) => writeGoogle_Value(w, messageValue)); }
  }
  w.unknown(value);
}
function readGoogle_ListValue(r: Reader, base?: Google_ListValue): Google_ListValue {
  const values: Array<Google_Value> = [...(base?.values ?? [])];
  const _unknown: Uint8Array[] = [...(base?._unknown ?? [])];
  while (!r.done) { const f = r.field(); switch (f.number) {
    case 1: { r.expect(f, 2);
      values.push(readGoogle_Value(r.child(), undefined));
      break; }
    default: _unknown.push(r.unknown(f)); break;
  } }
  return { _unknown, values };
}

export interface Ping extends UnknownFields {
}
export const Ping = {
  encode(value: Ping, limits?: WireLimits): Uint8Array<ArrayBuffer> { const w = new Writer(limits); writePing(w, value); return w.finish(); },
  decode(bytes: Uint8Array, limits?: WireLimits): Ping { return readPing(new Reader(bytes, limits)); },
};
function writePing(w: Writer, value: Ping): void {
  w.unknown(value);
}
function readPing(r: Reader, base?: Ping): Ping {
  const _unknown: Uint8Array[] = [...(base?._unknown ?? [])];
  while (!r.done) { const f = r.field(); switch (f.number) {
    default: _unknown.push(r.unknown(f)); break;
  } }
  return { _unknown };
}

export interface RequestSchema extends UnknownFields {
}
export const RequestSchema = {
  encode(value: RequestSchema, limits?: WireLimits): Uint8Array<ArrayBuffer> { const w = new Writer(limits); writeRequestSchema(w, value); return w.finish(); },
  decode(bytes: Uint8Array, limits?: WireLimits): RequestSchema { return readRequestSchema(new Reader(bytes, limits)); },
};
function writeRequestSchema(w: Writer, value: RequestSchema): void {
  w.unknown(value);
}
function readRequestSchema(r: Reader, base?: RequestSchema): RequestSchema {
  const _unknown: Uint8Array[] = [...(base?._unknown ?? [])];
  while (!r.done) { const f = r.field(); switch (f.number) {
    default: _unknown.push(r.unknown(f)); break;
  } }
  return { _unknown };
}

export interface ModelSchema extends UnknownFields {
  openapi?: Google_Struct;
}
export const ModelSchema = {
  encode(value: ModelSchema, limits?: WireLimits): Uint8Array<ArrayBuffer> { const w = new Writer(limits); writeModelSchema(w, value); return w.finish(); },
  decode(bytes: Uint8Array, limits?: WireLimits): ModelSchema { return readModelSchema(new Reader(bytes, limits)); },
};
function writeModelSchema(w: Writer, value: ModelSchema): void {
  if (value.openapi !== undefined) {
    { const messageValue = value.openapi; w.message(1, (w) => writeGoogle_Struct(w, messageValue)); }
  }
  w.unknown(value);
}
function readModelSchema(r: Reader, base?: ModelSchema): ModelSchema {
  let openapi: Google_Struct | undefined = base?.openapi;
  const _unknown: Uint8Array[] = [...(base?._unknown ?? [])];
  while (!r.done) { const f = r.field(); switch (f.number) {
    case 1: { r.expect(f, 2);
      openapi = readGoogle_Struct(r.child(), openapi);
      break; }
    default: _unknown.push(r.unknown(f)); break;
  } }
  return { _unknown, ...(openapi === undefined ? {} : { openapi }) };
}

export interface FileUploaded extends UnknownFields {
  upload_id: string;
  name: string;
  mime_type: string;
  size: bigint;
}
export const FileUploaded = {
  encode(value: FileUploaded, limits?: WireLimits): Uint8Array<ArrayBuffer> { const w = new Writer(limits); writeFileUploaded(w, value); return w.finish(); },
  decode(bytes: Uint8Array, limits?: WireLimits): FileUploaded { return readFileUploaded(new Reader(bytes, limits)); },
};
function writeFileUploaded(w: Writer, value: FileUploaded): void {
  if (value.upload_id !== "") {
    w.string(1, value.upload_id);
  }
  if (value.name !== "") {
    w.string(2, value.name);
  }
  if (value.mime_type !== "") {
    w.string(3, value.mime_type);
  }
  if (value.size !== 0n) {
    w.int64(4, value.size);
  }
  w.unknown(value);
}
function readFileUploaded(r: Reader, base?: FileUploaded): FileUploaded {
  let upload_id: string = base?.upload_id ?? "";
  let name: string = base?.name ?? "";
  let mime_type: string = base?.mime_type ?? "";
  let size: bigint = base?.size ?? 0n;
  const _unknown: Uint8Array[] = [...(base?._unknown ?? [])];
  while (!r.done) { const f = r.field(); switch (f.number) {
    case 1: { r.expect(f, 2);
      upload_id = r.string();
      break; }
    case 2: { r.expect(f, 2);
      name = r.string();
      break; }
    case 3: { r.expect(f, 2);
      mime_type = r.string();
      break; }
    case 4: { r.expect(f, 0);
      size = r.int64();
      break; }
    default: _unknown.push(r.unknown(f)); break;
  } }
  return { _unknown, upload_id, name, mime_type, size };
}

export interface RequestClip extends UnknownFields {
  duration_seconds: number;
}
export const RequestClip = {
  encode(value: RequestClip, limits?: WireLimits): Uint8Array<ArrayBuffer> { const w = new Writer(limits); writeRequestClip(w, value); return w.finish(); },
  decode(bytes: Uint8Array, limits?: WireLimits): RequestClip { return readRequestClip(new Reader(bytes, limits)); },
};
function writeRequestClip(w: Writer, value: RequestClip): void {
  if (value.duration_seconds !== 0 || Object.is(value.duration_seconds, -0)) {
    w.double(1, value.duration_seconds);
  }
  w.unknown(value);
}
function readRequestClip(r: Reader, base?: RequestClip): RequestClip {
  let duration_seconds: number = base?.duration_seconds ?? 0;
  const _unknown: Uint8Array[] = [...(base?._unknown ?? [])];
  while (!r.done) { const f = r.field(); switch (f.number) {
    case 1: { r.expect(f, 1);
      duration_seconds = r.double();
      break; }
    default: _unknown.push(r.unknown(f)); break;
  } }
  return { _unknown, duration_seconds };
}

export interface RequestRecording extends UnknownFields {
}
export const RequestRecording = {
  encode(value: RequestRecording, limits?: WireLimits): Uint8Array<ArrayBuffer> { const w = new Writer(limits); writeRequestRecording(w, value); return w.finish(); },
  decode(bytes: Uint8Array, limits?: WireLimits): RequestRecording { return readRequestRecording(new Reader(bytes, limits)); },
};
function writeRequestRecording(w: Writer, value: RequestRecording): void {
  w.unknown(value);
}
function readRequestRecording(r: Reader, base?: RequestRecording): RequestRecording {
  const _unknown: Uint8Array[] = [...(base?._unknown ?? [])];
  while (!r.done) { const f = r.field(); switch (f.number) {
    default: _unknown.push(r.unknown(f)); break;
  } }
  return { _unknown };
}

export interface ClipReady extends UnknownFields {
  session_id: string;
  kind: string;
  start_marker: number;
  end_marker: number;
  now_marker: number;
  predicted_ready_at_ms: bigint;
  playlist_url: string;
}
export const ClipReady = {
  encode(value: ClipReady, limits?: WireLimits): Uint8Array<ArrayBuffer> { const w = new Writer(limits); writeClipReady(w, value); return w.finish(); },
  decode(bytes: Uint8Array, limits?: WireLimits): ClipReady { return readClipReady(new Reader(bytes, limits)); },
};
function writeClipReady(w: Writer, value: ClipReady): void {
  if (value.session_id !== "") {
    w.string(1, value.session_id);
  }
  if (value.kind !== "") {
    w.string(2, value.kind);
  }
  if (value.start_marker !== 0 || Object.is(value.start_marker, -0)) {
    w.double(3, value.start_marker);
  }
  if (value.end_marker !== 0 || Object.is(value.end_marker, -0)) {
    w.double(4, value.end_marker);
  }
  if (value.now_marker !== 0 || Object.is(value.now_marker, -0)) {
    w.double(5, value.now_marker);
  }
  if (value.predicted_ready_at_ms !== 0n) {
    w.int64(6, value.predicted_ready_at_ms);
  }
  if (value.playlist_url !== "") {
    w.string(7, value.playlist_url);
  }
  w.unknown(value);
}
function readClipReady(r: Reader, base?: ClipReady): ClipReady {
  let session_id: string = base?.session_id ?? "";
  let kind: string = base?.kind ?? "";
  let start_marker: number = base?.start_marker ?? 0;
  let end_marker: number = base?.end_marker ?? 0;
  let now_marker: number = base?.now_marker ?? 0;
  let predicted_ready_at_ms: bigint = base?.predicted_ready_at_ms ?? 0n;
  let playlist_url: string = base?.playlist_url ?? "";
  const _unknown: Uint8Array[] = [...(base?._unknown ?? [])];
  while (!r.done) { const f = r.field(); switch (f.number) {
    case 1: { r.expect(f, 2);
      session_id = r.string();
      break; }
    case 2: { r.expect(f, 2);
      kind = r.string();
      break; }
    case 3: { r.expect(f, 1);
      start_marker = r.double();
      break; }
    case 4: { r.expect(f, 1);
      end_marker = r.double();
      break; }
    case 5: { r.expect(f, 1);
      now_marker = r.double();
      break; }
    case 6: { r.expect(f, 0);
      predicted_ready_at_ms = r.int64();
      break; }
    case 7: { r.expect(f, 2);
      playlist_url = r.string();
      break; }
    default: _unknown.push(r.unknown(f)); break;
  } }
  return { _unknown, session_id, kind, start_marker, end_marker, now_marker, predicted_ready_at_ms, playlist_url };
}

export interface ClipFailed extends UnknownFields {
  reason: string;
}
export const ClipFailed = {
  encode(value: ClipFailed, limits?: WireLimits): Uint8Array<ArrayBuffer> { const w = new Writer(limits); writeClipFailed(w, value); return w.finish(); },
  decode(bytes: Uint8Array, limits?: WireLimits): ClipFailed { return readClipFailed(new Reader(bytes, limits)); },
};
function writeClipFailed(w: Writer, value: ClipFailed): void {
  if (value.reason !== "") {
    w.string(1, value.reason);
  }
  w.unknown(value);
}
function readClipFailed(r: Reader, base?: ClipFailed): ClipFailed {
  let reason: string = base?.reason ?? "";
  const _unknown: Uint8Array[] = [...(base?._unknown ?? [])];
  while (!r.done) { const f = r.field(); switch (f.number) {
    case 1: { r.expect(f, 2);
      reason = r.string();
      break; }
    default: _unknown.push(r.unknown(f)); break;
  } }
  return { _unknown, reason };
}

export interface Moderation extends UnknownFields {
  action: string;
  input_kind: string;
  command: string;
  categories: Array<string>;
  message: string;
}
export const Moderation = {
  encode(value: Moderation, limits?: WireLimits): Uint8Array<ArrayBuffer> { const w = new Writer(limits); writeModeration(w, value); return w.finish(); },
  decode(bytes: Uint8Array, limits?: WireLimits): Moderation { return readModeration(new Reader(bytes, limits)); },
};
function writeModeration(w: Writer, value: Moderation): void {
  if (value.action !== "") {
    w.string(1, value.action);
  }
  if (value.input_kind !== "") {
    w.string(2, value.input_kind);
  }
  if (value.command !== "") {
    w.string(3, value.command);
  }
  for (const item of value.categories) {
    w.string(4, item);
  }
  if (value.message !== "") {
    w.string(5, value.message);
  }
  w.unknown(value);
}
function readModeration(r: Reader, base?: Moderation): Moderation {
  let action: string = base?.action ?? "";
  let input_kind: string = base?.input_kind ?? "";
  let command: string = base?.command ?? "";
  const categories: Array<string> = [...(base?.categories ?? [])];
  let message: string = base?.message ?? "";
  const _unknown: Uint8Array[] = [...(base?._unknown ?? [])];
  while (!r.done) { const f = r.field(); switch (f.number) {
    case 1: { r.expect(f, 2);
      action = r.string();
      break; }
    case 2: { r.expect(f, 2);
      input_kind = r.string();
      break; }
    case 3: { r.expect(f, 2);
      command = r.string();
      break; }
    case 4: { r.expect(f, 2);
      categories.push(r.string());
      break; }
    case 5: { r.expect(f, 2);
      message = r.string();
      break; }
    default: _unknown.push(r.unknown(f)); break;
  } }
  return { _unknown, action, input_kind, command, categories, message };
}

export interface PublishTrack extends UnknownFields {
  name: string;
}
export const PublishTrack = {
  encode(value: PublishTrack, limits?: WireLimits): Uint8Array<ArrayBuffer> { const w = new Writer(limits); writePublishTrack(w, value); return w.finish(); },
  decode(bytes: Uint8Array, limits?: WireLimits): PublishTrack { return readPublishTrack(new Reader(bytes, limits)); },
};
function writePublishTrack(w: Writer, value: PublishTrack): void {
  if (value.name !== "") {
    w.string(1, value.name);
  }
  w.unknown(value);
}
function readPublishTrack(r: Reader, base?: PublishTrack): PublishTrack {
  let name: string = base?.name ?? "";
  const _unknown: Uint8Array[] = [...(base?._unknown ?? [])];
  while (!r.done) { const f = r.field(); switch (f.number) {
    case 1: { r.expect(f, 2);
      name = r.string();
      break; }
    default: _unknown.push(r.unknown(f)); break;
  } }
  return { _unknown, name };
}

export interface PauseTrack extends UnknownFields {
  name: string;
}
export const PauseTrack = {
  encode(value: PauseTrack, limits?: WireLimits): Uint8Array<ArrayBuffer> { const w = new Writer(limits); writePauseTrack(w, value); return w.finish(); },
  decode(bytes: Uint8Array, limits?: WireLimits): PauseTrack { return readPauseTrack(new Reader(bytes, limits)); },
};
function writePauseTrack(w: Writer, value: PauseTrack): void {
  if (value.name !== "") {
    w.string(1, value.name);
  }
  w.unknown(value);
}
function readPauseTrack(r: Reader, base?: PauseTrack): PauseTrack {
  let name: string = base?.name ?? "";
  const _unknown: Uint8Array[] = [...(base?._unknown ?? [])];
  while (!r.done) { const f = r.field(); switch (f.number) {
    case 1: { r.expect(f, 2);
      name = r.string();
      break; }
    default: _unknown.push(r.unknown(f)); break;
  } }
  return { _unknown, name };
}

export interface ResumeTrack extends UnknownFields {
  name: string;
}
export const ResumeTrack = {
  encode(value: ResumeTrack, limits?: WireLimits): Uint8Array<ArrayBuffer> { const w = new Writer(limits); writeResumeTrack(w, value); return w.finish(); },
  decode(bytes: Uint8Array, limits?: WireLimits): ResumeTrack { return readResumeTrack(new Reader(bytes, limits)); },
};
function writeResumeTrack(w: Writer, value: ResumeTrack): void {
  if (value.name !== "") {
    w.string(1, value.name);
  }
  w.unknown(value);
}
function readResumeTrack(r: Reader, base?: ResumeTrack): ResumeTrack {
  let name: string = base?.name ?? "";
  const _unknown: Uint8Array[] = [...(base?._unknown ?? [])];
  while (!r.done) { const f = r.field(); switch (f.number) {
    case 1: { r.expect(f, 2);
      name = r.string();
      break; }
    default: _unknown.push(r.unknown(f)); break;
  } }
  return { _unknown, name };
}

export interface UnpublishTrack extends UnknownFields {
  name: string;
}
export const UnpublishTrack = {
  encode(value: UnpublishTrack, limits?: WireLimits): Uint8Array<ArrayBuffer> { const w = new Writer(limits); writeUnpublishTrack(w, value); return w.finish(); },
  decode(bytes: Uint8Array, limits?: WireLimits): UnpublishTrack { return readUnpublishTrack(new Reader(bytes, limits)); },
};
function writeUnpublishTrack(w: Writer, value: UnpublishTrack): void {
  if (value.name !== "") {
    w.string(1, value.name);
  }
  w.unknown(value);
}
function readUnpublishTrack(r: Reader, base?: UnpublishTrack): UnpublishTrack {
  let name: string = base?.name ?? "";
  const _unknown: Uint8Array[] = [...(base?._unknown ?? [])];
  while (!r.done) { const f = r.field(); switch (f.number) {
    case 1: { r.expect(f, 2);
      name = r.string();
      break; }
    default: _unknown.push(r.unknown(f)); break;
  } }
  return { _unknown, name };
}

export interface PublishTrackResponse extends UnknownFields {
  name: string;
}
export const PublishTrackResponse = {
  encode(value: PublishTrackResponse, limits?: WireLimits): Uint8Array<ArrayBuffer> { const w = new Writer(limits); writePublishTrackResponse(w, value); return w.finish(); },
  decode(bytes: Uint8Array, limits?: WireLimits): PublishTrackResponse { return readPublishTrackResponse(new Reader(bytes, limits)); },
};
function writePublishTrackResponse(w: Writer, value: PublishTrackResponse): void {
  if (value.name !== "") {
    w.string(1, value.name);
  }
  w.unknown(value);
}
function readPublishTrackResponse(r: Reader, base?: PublishTrackResponse): PublishTrackResponse {
  let name: string = base?.name ?? "";
  const _unknown: Uint8Array[] = [...(base?._unknown ?? [])];
  while (!r.done) { const f = r.field(); switch (f.number) {
    case 1: { r.expect(f, 2);
      name = r.string();
      break; }
    default: _unknown.push(r.unknown(f)); break;
  } }
  return { _unknown, name };
}

export interface ControlClientMessage extends UnknownFields {
  request_id: string;
  kind: number;
  payload?: { case: "ping"; value: Ping } | { case: "request_schema"; value: RequestSchema } | { case: "file_uploaded"; value: FileUploaded } | { case: "request_clip"; value: RequestClip } | { case: "request_recording"; value: RequestRecording } | { case: "publish_track"; value: PublishTrack } | { case: "pause_track"; value: PauseTrack } | { case: "resume_track"; value: ResumeTrack } | { case: "unpublish_track"; value: UnpublishTrack } | { case: "error"; value: Error };
}
export const ControlClientMessage = {
  encode(value: ControlClientMessage, limits?: WireLimits): Uint8Array<ArrayBuffer> { const w = new Writer(limits); writeControlClientMessage(w, value); return w.finish(); },
  decode(bytes: Uint8Array, limits?: WireLimits): ControlClientMessage { return readControlClientMessage(new Reader(bytes, limits)); },
};
function writeControlClientMessage(w: Writer, value: ControlClientMessage): void {
  if (value.request_id !== "") {
    w.string(1, value.request_id);
  }
  if (value.kind !== 0) {
    w.int32(2, value.kind);
  }
  if (value.payload?.case === "ping") {
    { const messageValue = value.payload.value; w.message(10, (w) => writePing(w, messageValue)); }
  }
  if (value.payload?.case === "request_schema") {
    { const messageValue = value.payload.value; w.message(11, (w) => writeRequestSchema(w, messageValue)); }
  }
  if (value.payload?.case === "file_uploaded") {
    { const messageValue = value.payload.value; w.message(12, (w) => writeFileUploaded(w, messageValue)); }
  }
  if (value.payload?.case === "request_clip") {
    { const messageValue = value.payload.value; w.message(13, (w) => writeRequestClip(w, messageValue)); }
  }
  if (value.payload?.case === "request_recording") {
    { const messageValue = value.payload.value; w.message(14, (w) => writeRequestRecording(w, messageValue)); }
  }
  if (value.payload?.case === "publish_track") {
    { const messageValue = value.payload.value; w.message(15, (w) => writePublishTrack(w, messageValue)); }
  }
  if (value.payload?.case === "pause_track") {
    { const messageValue = value.payload.value; w.message(16, (w) => writePauseTrack(w, messageValue)); }
  }
  if (value.payload?.case === "resume_track") {
    { const messageValue = value.payload.value; w.message(17, (w) => writeResumeTrack(w, messageValue)); }
  }
  if (value.payload?.case === "unpublish_track") {
    { const messageValue = value.payload.value; w.message(18, (w) => writeUnpublishTrack(w, messageValue)); }
  }
  if (value.payload?.case === "error") {
    { const messageValue = value.payload.value; w.message(40, (w) => writeError(w, messageValue)); }
  }
  w.unknown(value);
}
function readControlClientMessage(r: Reader, base?: ControlClientMessage): ControlClientMessage {
  let request_id: string = base?.request_id ?? "";
  let kind: number = base?.kind ?? 0;
  let payload: ControlClientMessage["payload"] = base?.payload;
  const _unknown: Uint8Array[] = [...(base?._unknown ?? [])];
  while (!r.done) { const f = r.field(); switch (f.number) {
    case 1: { r.expect(f, 2);
      request_id = r.string();
      break; }
    case 2: { r.expect(f, 0);
      kind = r.int32();
      break; }
    case 10: { r.expect(f, 2);
      payload = { case: "ping", value: readPing(r.child(), payload?.case === "ping" ? payload.value : undefined) };
      break; }
    case 11: { r.expect(f, 2);
      payload = { case: "request_schema", value: readRequestSchema(r.child(), payload?.case === "request_schema" ? payload.value : undefined) };
      break; }
    case 12: { r.expect(f, 2);
      payload = { case: "file_uploaded", value: readFileUploaded(r.child(), payload?.case === "file_uploaded" ? payload.value : undefined) };
      break; }
    case 13: { r.expect(f, 2);
      payload = { case: "request_clip", value: readRequestClip(r.child(), payload?.case === "request_clip" ? payload.value : undefined) };
      break; }
    case 14: { r.expect(f, 2);
      payload = { case: "request_recording", value: readRequestRecording(r.child(), payload?.case === "request_recording" ? payload.value : undefined) };
      break; }
    case 15: { r.expect(f, 2);
      payload = { case: "publish_track", value: readPublishTrack(r.child(), payload?.case === "publish_track" ? payload.value : undefined) };
      break; }
    case 16: { r.expect(f, 2);
      payload = { case: "pause_track", value: readPauseTrack(r.child(), payload?.case === "pause_track" ? payload.value : undefined) };
      break; }
    case 17: { r.expect(f, 2);
      payload = { case: "resume_track", value: readResumeTrack(r.child(), payload?.case === "resume_track" ? payload.value : undefined) };
      break; }
    case 18: { r.expect(f, 2);
      payload = { case: "unpublish_track", value: readUnpublishTrack(r.child(), payload?.case === "unpublish_track" ? payload.value : undefined) };
      break; }
    case 40: { r.expect(f, 2);
      payload = { case: "error", value: readError(r.child(), payload?.case === "error" ? payload.value : undefined) };
      break; }
    default: _unknown.push(r.unknown(f)); break;
  } }
  return { _unknown, request_id, kind, ...(payload === undefined ? {} : { payload }) };
}

export interface ControlServerMessage extends UnknownFields {
  request_id: string;
  kind: number;
  payload?: { case: "model_schema"; value: ModelSchema } | { case: "clip_ready"; value: ClipReady } | { case: "clip_failed"; value: ClipFailed } | { case: "moderation"; value: Moderation } | { case: "publish_track"; value: PublishTrackResponse } | { case: "error"; value: Error };
}
export const ControlServerMessage = {
  encode(value: ControlServerMessage, limits?: WireLimits): Uint8Array<ArrayBuffer> { const w = new Writer(limits); writeControlServerMessage(w, value); return w.finish(); },
  decode(bytes: Uint8Array, limits?: WireLimits): ControlServerMessage { return readControlServerMessage(new Reader(bytes, limits)); },
};
function writeControlServerMessage(w: Writer, value: ControlServerMessage): void {
  if (value.request_id !== "") {
    w.string(1, value.request_id);
  }
  if (value.kind !== 0) {
    w.int32(2, value.kind);
  }
  if (value.payload?.case === "model_schema") {
    { const messageValue = value.payload.value; w.message(10, (w) => writeModelSchema(w, messageValue)); }
  }
  if (value.payload?.case === "clip_ready") {
    { const messageValue = value.payload.value; w.message(11, (w) => writeClipReady(w, messageValue)); }
  }
  if (value.payload?.case === "clip_failed") {
    { const messageValue = value.payload.value; w.message(12, (w) => writeClipFailed(w, messageValue)); }
  }
  if (value.payload?.case === "moderation") {
    { const messageValue = value.payload.value; w.message(13, (w) => writeModeration(w, messageValue)); }
  }
  if (value.payload?.case === "publish_track") {
    { const messageValue = value.payload.value; w.message(14, (w) => writePublishTrackResponse(w, messageValue)); }
  }
  if (value.payload?.case === "error") {
    { const messageValue = value.payload.value; w.message(40, (w) => writeError(w, messageValue)); }
  }
  w.unknown(value);
}
function readControlServerMessage(r: Reader, base?: ControlServerMessage): ControlServerMessage {
  let request_id: string = base?.request_id ?? "";
  let kind: number = base?.kind ?? 0;
  let payload: ControlServerMessage["payload"] = base?.payload;
  const _unknown: Uint8Array[] = [...(base?._unknown ?? [])];
  while (!r.done) { const f = r.field(); switch (f.number) {
    case 1: { r.expect(f, 2);
      request_id = r.string();
      break; }
    case 2: { r.expect(f, 0);
      kind = r.int32();
      break; }
    case 10: { r.expect(f, 2);
      payload = { case: "model_schema", value: readModelSchema(r.child(), payload?.case === "model_schema" ? payload.value : undefined) };
      break; }
    case 11: { r.expect(f, 2);
      payload = { case: "clip_ready", value: readClipReady(r.child(), payload?.case === "clip_ready" ? payload.value : undefined) };
      break; }
    case 12: { r.expect(f, 2);
      payload = { case: "clip_failed", value: readClipFailed(r.child(), payload?.case === "clip_failed" ? payload.value : undefined) };
      break; }
    case 13: { r.expect(f, 2);
      payload = { case: "moderation", value: readModeration(r.child(), payload?.case === "moderation" ? payload.value : undefined) };
      break; }
    case 14: { r.expect(f, 2);
      payload = { case: "publish_track", value: readPublishTrackResponse(r.child(), payload?.case === "publish_track" ? payload.value : undefined) };
      break; }
    case 40: { r.expect(f, 2);
      payload = { case: "error", value: readError(r.child(), payload?.case === "error" ? payload.value : undefined) };
      break; }
    default: _unknown.push(r.unknown(f)); break;
  } }
  return { _unknown, request_id, kind, ...(payload === undefined ? {} : { payload }) };
}

export interface UploadReference extends UnknownFields {
  upload_id: string;
  name: string;
  mime_type: string;
  size: bigint;
}
export const UploadReference = {
  encode(value: UploadReference, limits?: WireLimits): Uint8Array<ArrayBuffer> { const w = new Writer(limits); writeUploadReference(w, value); return w.finish(); },
  decode(bytes: Uint8Array, limits?: WireLimits): UploadReference { return readUploadReference(new Reader(bytes, limits)); },
};
function writeUploadReference(w: Writer, value: UploadReference): void {
  if (value.upload_id !== "") {
    w.string(1, value.upload_id);
  }
  if (value.name !== "") {
    w.string(2, value.name);
  }
  if (value.mime_type !== "") {
    w.string(3, value.mime_type);
  }
  if (value.size !== 0n) {
    w.int64(4, value.size);
  }
  w.unknown(value);
}
function readUploadReference(r: Reader, base?: UploadReference): UploadReference {
  let upload_id: string = base?.upload_id ?? "";
  let name: string = base?.name ?? "";
  let mime_type: string = base?.mime_type ?? "";
  let size: bigint = base?.size ?? 0n;
  const _unknown: Uint8Array[] = [...(base?._unknown ?? [])];
  while (!r.done) { const f = r.field(); switch (f.number) {
    case 1: { r.expect(f, 2);
      upload_id = r.string();
      break; }
    case 2: { r.expect(f, 2);
      name = r.string();
      break; }
    case 3: { r.expect(f, 2);
      mime_type = r.string();
      break; }
    case 4: { r.expect(f, 0);
      size = r.int64();
      break; }
    default: _unknown.push(r.unknown(f)); break;
  } }
  return { _unknown, upload_id, name, mime_type, size };
}

export interface Command extends UnknownFields {
  type: string;
  data?: Google_Struct;
  uploads: Map<string, UploadReference>;
}
export const Command = {
  encode(value: Command, limits?: WireLimits): Uint8Array<ArrayBuffer> { const w = new Writer(limits); writeCommand(w, value); return w.finish(); },
  decode(bytes: Uint8Array, limits?: WireLimits): Command { return readCommand(new Reader(bytes, limits)); },
};
function writeCommand(w: Writer, value: Command): void {
  if (value.type !== "") {
    w.string(1, value.type);
  }
  if (value.data !== undefined) {
    { const messageValue = value.data; w.message(2, (w) => writeGoogle_Struct(w, messageValue)); }
  }
  for (const [key, item] of value.uploads) w.message(3, (w) => writeCommand_UploadsEntry(w, { key, value: item }));
  w.unknown(value);
}
function readCommand(r: Reader, base?: Command): Command {
  let type: string = base?.type ?? "";
  let data: Google_Struct | undefined = base?.data;
  const uploads: Map<string, UploadReference> = new Map(base?.uploads ?? []);
  const _unknown: Uint8Array[] = [...(base?._unknown ?? [])];
  while (!r.done) { const f = r.field(); switch (f.number) {
    case 1: { r.expect(f, 2);
      type = r.string();
      break; }
    case 2: { r.expect(f, 2);
      data = readGoogle_Struct(r.child(), data);
      break; }
    case 3: { r.expect(f, 2);
      const entry = readCommand_UploadsEntry(r.child(), undefined); uploads.set(entry.key, entry.value ?? UploadReference.decode(new Uint8Array()));
      break; }
    default: _unknown.push(r.unknown(f)); break;
  } }
  return { _unknown, type, ...(data === undefined ? {} : { data }), uploads };
}

export interface Command_UploadsEntry extends UnknownFields {
  key: string;
  value?: UploadReference;
}
export const Command_UploadsEntry = {
  encode(value: Command_UploadsEntry, limits?: WireLimits): Uint8Array<ArrayBuffer> { const w = new Writer(limits); writeCommand_UploadsEntry(w, value); return w.finish(); },
  decode(bytes: Uint8Array, limits?: WireLimits): Command_UploadsEntry { return readCommand_UploadsEntry(new Reader(bytes, limits)); },
};
function writeCommand_UploadsEntry(w: Writer, value: Command_UploadsEntry): void {
  if (value.key !== "") {
    w.string(1, value.key);
  }
  if (value.value !== undefined) {
    { const messageValue = value.value; w.message(2, (w) => writeUploadReference(w, messageValue)); }
  }
  w.unknown(value);
}
function readCommand_UploadsEntry(r: Reader, base?: Command_UploadsEntry): Command_UploadsEntry {
  let key: string = base?.key ?? "";
  let value: UploadReference | undefined = base?.value;
  const _unknown: Uint8Array[] = [...(base?._unknown ?? [])];
  while (!r.done) { const f = r.field(); switch (f.number) {
    case 1: { r.expect(f, 2);
      key = r.string();
      break; }
    case 2: { r.expect(f, 2);
      value = readUploadReference(r.child(), value);
      break; }
    default: _unknown.push(r.unknown(f)); break;
  } }
  return { _unknown, key, ...(value === undefined ? {} : { value }) };
}

export interface ModelMessage extends UnknownFields {
  type: string;
  data?: Google_Struct;
}
export const ModelMessage = {
  encode(value: ModelMessage, limits?: WireLimits): Uint8Array<ArrayBuffer> { const w = new Writer(limits); writeModelMessage(w, value); return w.finish(); },
  decode(bytes: Uint8Array, limits?: WireLimits): ModelMessage { return readModelMessage(new Reader(bytes, limits)); },
};
function writeModelMessage(w: Writer, value: ModelMessage): void {
  if (value.type !== "") {
    w.string(1, value.type);
  }
  if (value.data !== undefined) {
    { const messageValue = value.data; w.message(2, (w) => writeGoogle_Struct(w, messageValue)); }
  }
  w.unknown(value);
}
function readModelMessage(r: Reader, base?: ModelMessage): ModelMessage {
  let type: string = base?.type ?? "";
  let data: Google_Struct | undefined = base?.data;
  const _unknown: Uint8Array[] = [...(base?._unknown ?? [])];
  while (!r.done) { const f = r.field(); switch (f.number) {
    case 1: { r.expect(f, 2);
      type = r.string();
      break; }
    case 2: { r.expect(f, 2);
      data = readGoogle_Struct(r.child(), data);
      break; }
    default: _unknown.push(r.unknown(f)); break;
  } }
  return { _unknown, type, ...(data === undefined ? {} : { data }) };
}

export interface DataClientMessage extends UnknownFields {
  request_id: string;
  kind: number;
  payload?: { case: "command"; value: Command } | { case: "error"; value: Error };
}
export const DataClientMessage = {
  encode(value: DataClientMessage, limits?: WireLimits): Uint8Array<ArrayBuffer> { const w = new Writer(limits); writeDataClientMessage(w, value); return w.finish(); },
  decode(bytes: Uint8Array, limits?: WireLimits): DataClientMessage { return readDataClientMessage(new Reader(bytes, limits)); },
};
function writeDataClientMessage(w: Writer, value: DataClientMessage): void {
  if (value.request_id !== "") {
    w.string(1, value.request_id);
  }
  if (value.kind !== 0) {
    w.int32(2, value.kind);
  }
  if (value.payload?.case === "command") {
    { const messageValue = value.payload.value; w.message(10, (w) => writeCommand(w, messageValue)); }
  }
  if (value.payload?.case === "error") {
    { const messageValue = value.payload.value; w.message(40, (w) => writeError(w, messageValue)); }
  }
  w.unknown(value);
}
function readDataClientMessage(r: Reader, base?: DataClientMessage): DataClientMessage {
  let request_id: string = base?.request_id ?? "";
  let kind: number = base?.kind ?? 0;
  let payload: DataClientMessage["payload"] = base?.payload;
  const _unknown: Uint8Array[] = [...(base?._unknown ?? [])];
  while (!r.done) { const f = r.field(); switch (f.number) {
    case 1: { r.expect(f, 2);
      request_id = r.string();
      break; }
    case 2: { r.expect(f, 0);
      kind = r.int32();
      break; }
    case 10: { r.expect(f, 2);
      payload = { case: "command", value: readCommand(r.child(), payload?.case === "command" ? payload.value : undefined) };
      break; }
    case 40: { r.expect(f, 2);
      payload = { case: "error", value: readError(r.child(), payload?.case === "error" ? payload.value : undefined) };
      break; }
    default: _unknown.push(r.unknown(f)); break;
  } }
  return { _unknown, request_id, kind, ...(payload === undefined ? {} : { payload }) };
}

export interface DataServerMessage extends UnknownFields {
  request_id: string;
  kind: number;
  payload?: { case: "message"; value: ModelMessage } | { case: "error"; value: Error };
}
export const DataServerMessage = {
  encode(value: DataServerMessage, limits?: WireLimits): Uint8Array<ArrayBuffer> { const w = new Writer(limits); writeDataServerMessage(w, value); return w.finish(); },
  decode(bytes: Uint8Array, limits?: WireLimits): DataServerMessage { return readDataServerMessage(new Reader(bytes, limits)); },
};
function writeDataServerMessage(w: Writer, value: DataServerMessage): void {
  if (value.request_id !== "") {
    w.string(1, value.request_id);
  }
  if (value.kind !== 0) {
    w.int32(2, value.kind);
  }
  if (value.payload?.case === "message") {
    { const messageValue = value.payload.value; w.message(10, (w) => writeModelMessage(w, messageValue)); }
  }
  if (value.payload?.case === "error") {
    { const messageValue = value.payload.value; w.message(40, (w) => writeError(w, messageValue)); }
  }
  w.unknown(value);
}
function readDataServerMessage(r: Reader, base?: DataServerMessage): DataServerMessage {
  let request_id: string = base?.request_id ?? "";
  let kind: number = base?.kind ?? 0;
  let payload: DataServerMessage["payload"] = base?.payload;
  const _unknown: Uint8Array[] = [...(base?._unknown ?? [])];
  while (!r.done) { const f = r.field(); switch (f.number) {
    case 1: { r.expect(f, 2);
      request_id = r.string();
      break; }
    case 2: { r.expect(f, 0);
      kind = r.int32();
      break; }
    case 10: { r.expect(f, 2);
      payload = { case: "message", value: readModelMessage(r.child(), payload?.case === "message" ? payload.value : undefined) };
      break; }
    case 40: { r.expect(f, 2);
      payload = { case: "error", value: readError(r.child(), payload?.case === "error" ? payload.value : undefined) };
      break; }
    default: _unknown.push(r.unknown(f)); break;
  } }
  return { _unknown, request_id, kind, ...(payload === undefined ? {} : { payload }) };
}
